### ISSUE TITLE
Following CentOS 7 guide results in issues

### ISSUE THREAD

**Issue by Sil3ntPr0digy** [GameServerManagers/LinuxGSM#1377]
Following the [CentOS 7 tmux upgrade guide](https://github.com/GameServerManagers/LinuxGSM/wiki/Tmux#installing-the-latest-tmux-from-source-on-centos-7 ) results in tmux -V returning "tmux master" which breaks embedded version checks for tmux.

![tmux3](https://cloud.githubusercontent.com/assets/2136965/24125259/34c8c7d8-0d9e-11e7-944e-c1d063e94b0e.png)

Also just a note, the CentOS 7 guide needs to be updated, as 
![tmux2](https://cloud.githubusercontent.com/assets/2136965/24125244/267421b4-0d9e-11e7-88a6-7db06eb5bfd9.png)
this is what you will see if you attempt to do sudo make install, rather, you have to manually copy the made tmux over to /usr/local/bin/tmux and then manually change the path.

**Comment by ChaosMTA** [comment]
Fixed the wiki entry.

**Comment by dgibbs64** [comment]
can this be closed?

**Comment by ChaosMTA** [comment]
Yes, I edited the guide with proper instructions now.

**Comment by Sil3ntPr0digy** [comment]
Actually the fixes haven't been pushed to all branches yet, the tmux version check error was still occurring on some branches last I checked.

**Comment by ChaosMTA** [comment]
Note that my PR has been merged for the next LGSM release.

**Comment by Sil3ntPr0digy** [comment]
Ah, I typically leave tickets open until it has been merged lol. Alright. :3
