### ISSUE TITLE
[BUG] [Garry's Mod] Update command fails

### ISSUE THREAD

**Issue by peter-r-g** [GameServerManagers/LinuxGSM#3140]
## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Garry's Mod]
* **Command:** [Update]
* **LinuxGSM version:** [v20.6.2]

## Further Information

Changing the branch within the configuration file seems to break the update command. If there is no branch set, the update command works fine. Setting it to anything else (even if a valid depot) will always result in the same error. For some reason if you use the validate command then it all works fine and it seems to update to the new depot.

Looking at the script log I found this:
```
Dec 22 18:26:33.509 gmodserver: UPDATE: INFO: Using anonymous Steam login
Dec 22 18:26:35.101 gmodserver: UPDATE: PASS: Checking local build
Dec 22 18:26:41.076 gmodserver: UPDATE: FATAL: Checking remote build
Dec 22 18:26:41.081 gmodserver: UPDATE: INFO: LinuxGSM version: v20.6.2
Dec 22 18:26:41.082 gmodserver: UPDATE: FATAL: core_exit.sh exiting with code: 1
```

## To Reproduce

Steps to reproduce the behaviour:
1. Set branch to "x86-64" (64 bit beta to dedicated server, https://steamdb.info/app/4020/depots/?branch=x86-64)
2. Use update command (./gmodserver update)
3. See error "[ FAIL ] Updating gmodserver: Checking remote build: SteamCMD"

## Expected behaviour

A success message and that my files are updated to the x86-64 branch of the dedicated server.

**Comment by h3o66** [comment]
should be proably fixed with #3139

**Comment by peter-r-g** [comment]
> 
> 
> should be proably fixed with #3139

Can confirm that change fixes this issue

**Comment by h3o66** [comment]
> > should be proably fixed with #3139
> 
> Can confirm that change fixes this issue

thanks for confirming this

**Comment by brandonsturgeon** [comment]
Also can confirm, applied that change locally and it works.
However, still getting the error even after updating lgsm. Are we still waiting on a deployment?

**Comment by h3o66** [comment]
> Also can confirm, applied that change locally and it works.
> However, still getting the error even after updating lgsm. Are we still waiting on a deployment?

yes, this will be done with the next release, what is currently in testing.
If you want to test it, you need to set it to the new release branch.
For further info please join the Discord
